name: PHP Workflow

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Audit dependencies
        run: composer audit

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer update --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts -o

      - name: PHPStan
        run: ./vendor/bin/phpstan analyse --error-format github --level=max src

      - name: PHP-CS-Fixer
        run: ./vendor/bin/php-cs-fixer --format=json check

      - name: Pest
        run: XDEBUG_MODE=coverage ./vendor/bin/pest --coverage --coverage-clover=coverage.xml
